// Deterministic synthetic atlas page.
//
// Real atlas pages in the consuming project reach 4032x4080 (~16 MP), and that size is the whole
// point: the failure mode this harness measures is a SMALL element whose display list references a
// LARGE source image, so the page must be realistically large or the decode cost under measurement
// disappears.
//
// Everything here is a pure function of `seed`, so the page can be regenerated byte-identically on
// any machine and must never be committed (gsw keeps generated artifacts ignored).
//
// The shapes are deliberately varied and textured. A flat-colour page would compress to nothing and
// would decode far faster than a real atlas, which would understate exactly the number we care about.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import sharp from "sharp";

export interface AtlasRegion {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface AtlasFixture {
  seed: number;
  pageSize: number;
  /** URL the browser loads the page from (set by the server, not the generator). */
  pageUrl: string;
  regions: AtlasRegion[];
}

export interface AtlasGenerateOptions {
  seed?: number;
  pageSize?: number;
  regionCount?: number;
  /**
   * Inset each region inside its grid cell by a deterministic jitter (the default). Turn it OFF to
   * get regions that are all exactly one cell — which is what makes every sprite of a fixed box size
   * resolve to the SAME `background-size`, i.e. ONE scaled decode of the page instead of N.
   *
   * That is the `scaleDiversity` scenario parameter's only mechanism: the sprite geometry is
   * identical either way, so the difference in the numbers is scale diversity and nothing else.
   */
  regionInset?: boolean;
  /**
   * Page height, when the page is not square. Defaults to `pageSize`, so every existing square atlas
   * is byte-identical to before.
   */
  pageHeight?: number;
  /**
   * Paint an opaque, textured full-bleed base under the shapes. Off for atlas pages (they need
   * transparent gutters); ON for the single large background image S4 puts beneath the sprites,
   * which is a rendered game screen: opaque, edge to edge, and expensive to decode.
   */
  opaqueBase?: boolean;
}

export const ATLAS_DEFAULTS = {
  seed: 1337,
  pageSize: 4096,
  regionCount: 100,
} as const;

/** Deterministic 32-bit PRNG (mulberry32). Same seed, same stream, on every platform. */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hash2(x: number, y: number, seed: number): number {
  let h = (x * 374761393 + y * 668265263 + seed * 2246822519) >>> 0;
  h = Math.imul(h ^ (h >>> 13), 1274126177) >>> 0;
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
}

function hsvToRgb(h: number, s: number, v: number): [number, number, number] {
  const i = Math.floor(h * 6);
  const f = h * 6 - i;
  const p = v * (1 - s);
  const q = v * (1 - f * s);
  const t = v * (1 - (1 - f) * s);
  const [r, g, b] = [
    [v, t, p],
    [q, v, p],
    [p, v, t],
    [p, q, v],
    [t, p, v],
    [v, p, q],
  ][i % 6];
  return [Math.round(r * 255), Math.round(g * 255), Math.round(b * 255)];
}

const SHAPE_KINDS = [
  "disc",
  "ring",
  "star",
  "triangle",
  "hex",
  "chevron",
  "cross",
  "rounded",
  "spiral",
  "diamond",
] as const;

/**
 * Region grid. `regionCount` regions are laid out on a square-ish grid over `pageSize`, each region
 * inset inside its cell by a deterministic margin so region rects are varied (a uniform grid would
 * let the crop math be accidentally right).
 */
export function atlasRegions(
  options: AtlasGenerateOptions = {},
): AtlasRegion[] {
  const {
    seed = ATLAS_DEFAULTS.seed,
    pageSize = ATLAS_DEFAULTS.pageSize,
    regionCount = ATLAS_DEFAULTS.regionCount,
    regionInset = true,
    pageHeight = pageSize,
  } = options;
  const cols = Math.ceil(Math.sqrt((regionCount * pageSize) / pageHeight));
  const rows = Math.ceil(regionCount / cols);
  const cellW = Math.floor(pageSize / cols);
  const cellH = Math.floor(pageHeight / rows);
  const random = mulberry32(seed ^ 0x9e3779b9);
  const regions: AtlasRegion[] = [];
  for (let i = 0; i < regionCount; i++) {
    const col = i % cols;
    const row = Math.floor(i / cols);
    // The random stream is consumed either way, so the two variants stay comparable seeds rather
    // than diverging into unrelated shape sequences.
    const maxInset = regionInset
      ? Math.floor(Math.min(cellW, cellH) * 0.18)
      : 0;
    const insetX = Math.floor(random() * maxInset);
    const insetY = Math.floor(random() * maxInset);
    const width = Math.max(4, cellW - insetX * 2);
    const height = Math.max(4, cellH - insetY * 2);
    regions.push({
      x: col * cellW + insetX,
      y: row * cellH + insetY,
      width,
      height,
    });
  }
  return regions;
}

/**
 * Raw RGBA page pixels. Pure and fast enough to unit-test at small sizes; the 4096 page takes a
 * couple of seconds, which is why callers go through `ensureAtlasFixture` and its on-disk cache.
 */
export function renderAtlasPixels(options: AtlasGenerateOptions = {}): {
  data: Buffer;
  pageSize: number;
  pageHeight: number;
  regions: AtlasRegion[];
} {
  const {
    seed = ATLAS_DEFAULTS.seed,
    pageSize = ATLAS_DEFAULTS.pageSize,
    opaqueBase = false,
  } = options;
  const pageHeight = options.pageHeight ?? pageSize;
  const regions = atlasRegions(options);
  const data = Buffer.alloc(pageSize * pageHeight * 4, 0);
  if (opaqueBase) {
    paintOpaqueBase(data, pageSize, pageHeight, seed);
  }

  for (let index = 0; index < regions.length; index++) {
    const region = regions[index];
    const random = mulberry32((seed * 2654435761 + index * 40503) >>> 0);
    const kind = SHAPE_KINDS[index % SHAPE_KINDS.length];
    const hue = (index * 0.61803398875 + random() * 0.05) % 1;
    const hue2 = (hue + 0.18 + random() * 0.2) % 1;
    const base = hsvToRgb(hue, 0.55 + random() * 0.4, 0.55 + random() * 0.4);
    const accent = hsvToRgb(hue2, 0.6 + random() * 0.35, 0.6 + random() * 0.35);
    const arms = 3 + Math.floor(random() * 6);
    const phase = random() * Math.PI * 2;
    // Coarse value-noise grid, bilinearly sampled: gives structured texture that costs real bytes
    // to encode without degenerating into incompressible white noise.
    const noiseN = 8;
    const noise = new Float32Array(noiseN * noiseN);
    for (let i = 0; i < noise.length; i++) {
      noise[i] = random();
    }
    const sampleNoise = (u: number, v: number): number => {
      const fx = u * (noiseN - 1);
      const fy = v * (noiseN - 1);
      const x0 = Math.min(noiseN - 1, Math.floor(fx));
      const y0 = Math.min(noiseN - 1, Math.floor(fy));
      const x1 = Math.min(noiseN - 1, x0 + 1);
      const y1 = Math.min(noiseN - 1, y0 + 1);
      const tx = fx - x0;
      const ty = fy - y0;
      const a = noise[y0 * noiseN + x0];
      const b = noise[y0 * noiseN + x1];
      const c = noise[y1 * noiseN + x0];
      const d = noise[y1 * noiseN + x1];
      return (
        a * (1 - tx) * (1 - ty) +
        b * tx * (1 - ty) +
        c * (1 - tx) * ty +
        d * tx * ty
      );
    };

    for (let py = 0; py < region.height; py++) {
      const v = py / (region.height - 1 || 1);
      const ny = v * 2 - 1;
      for (let px = 0; px < region.width; px++) {
        const u = px / (region.width - 1 || 1);
        const nx = u * 2 - 1;
        const r = Math.hypot(nx, ny);
        const theta = Math.atan2(ny, nx);
        let inside = false;
        switch (kind) {
          case "disc":
            inside = r <= 0.92;
            break;
          case "ring":
            inside = r <= 0.94 && r >= 0.52;
            break;
          case "star":
            inside =
              r <=
              0.35 + 0.55 * Math.abs(Math.cos(arms * (theta + phase) * 0.5));
            break;
          case "triangle":
            inside =
              ny <= 0.85 &&
              ny >= -0.85 - 0 &&
              Math.abs(nx) <= (0.85 - ny) * 0.55;
            break;
          case "hex": {
            const ax = Math.abs(nx);
            const ay = Math.abs(ny);
            inside = ax <= 0.86 && ay <= 0.86 && ax * 0.5 + ay * 0.866 <= 0.86;
            break;
          }
          case "chevron": {
            const d = Math.abs(ny - Math.abs(nx) * 0.9 + 0.3);
            inside = d <= 0.3 && Math.abs(nx) <= 0.9;
            break;
          }
          case "cross":
            inside =
              (Math.abs(nx) <= 0.28 && Math.abs(ny) <= 0.92) ||
              (Math.abs(ny) <= 0.28 && Math.abs(nx) <= 0.92);
            break;
          case "rounded": {
            const ax = Math.max(0, Math.abs(nx) - 0.55);
            const ay = Math.max(0, Math.abs(ny) - 0.55);
            inside =
              Math.hypot(ax, ay) <= 0.33 &&
              Math.abs(nx) <= 0.9 &&
              Math.abs(ny) <= 0.9;
            break;
          }
          case "spiral": {
            const spin = (theta + phase + Math.PI) / (Math.PI * 2);
            inside =
              r <= 0.95 && Math.abs(((r * arms + spin) % 1) - 0.5) < 0.28;
            break;
          }
          default:
            inside = Math.abs(nx) + Math.abs(ny) <= 0.92;
            break;
        }
        // Every region keeps a solid opaque core so a sprite's CENTRE pixel is guaranteed to be
        // non-background. The screenshot presence check samples exactly that point, and a hollow
        // shape would make a correct render look like a blank page.
        const core = r <= 0.16;
        if (!inside && !core) {
          continue;
        }
        const texture = sampleNoise(u, v);
        const dither = hash2(region.x + px, region.y + py, seed) * 0.14 - 0.07;
        const mix = core
          ? 1
          : Math.min(1, Math.max(0, texture * 0.75 + u * 0.25 + dither));
        const shade = core ? 1.12 : 0.72 + texture * 0.5 + dither;
        const offset = ((region.y + py) * pageSize + (region.x + px)) * 4;
        data[offset] = clamp255(
          (base[0] * (1 - mix) + accent[0] * mix) * shade,
        );
        data[offset + 1] = clamp255(
          (base[1] * (1 - mix) + accent[1] * mix) * shade,
        );
        data[offset + 2] = clamp255(
          (base[2] * (1 - mix) + accent[2] * mix) * shade,
        );
        data[offset + 3] = 255;
      }
    }
  }
  return { data, pageSize, pageHeight, regions };
}

/**
 * Opaque full-bleed base: a two-octave value-noise field over a vertical hue ramp. Structured, so it
 * costs real bytes to encode and real time to decode (a flat fill would compress to nothing and
 * understate exactly the cost S4 exists to measure), and fully opaque, so the presence guard can
 * sample it anywhere.
 */
function paintOpaqueBase(
  data: Buffer,
  width: number,
  height: number,
  seed: number,
): void {
  const random = mulberry32((seed * 2246822519 + 0x51ed) >>> 0);
  const coarseN = 12;
  const fineN = 41;
  const coarse = new Float32Array(coarseN * coarseN);
  const fine = new Float32Array(fineN * fineN);
  for (let i = 0; i < coarse.length; i++) {
    coarse[i] = random();
  }
  for (let i = 0; i < fine.length; i++) {
    fine[i] = random();
  }
  const sample = (
    grid: Float32Array,
    n: number,
    u: number,
    v: number,
  ): number => {
    const fx = u * (n - 1);
    const fy = v * (n - 1);
    const x0 = Math.min(n - 1, Math.floor(fx));
    const y0 = Math.min(n - 1, Math.floor(fy));
    const x1 = Math.min(n - 1, x0 + 1);
    const y1 = Math.min(n - 1, y0 + 1);
    const tx = fx - x0;
    const ty = fy - y0;
    return (
      grid[y0 * n + x0] * (1 - tx) * (1 - ty) +
      grid[y0 * n + x1] * tx * (1 - ty) +
      grid[y1 * n + x0] * (1 - tx) * ty +
      grid[y1 * n + x1] * tx * ty
    );
  };
  const hueBase = random();
  for (let y = 0; y < height; y++) {
    const v = height > 1 ? y / (height - 1) : 0;
    for (let x = 0; x < width; x++) {
      const u = width > 1 ? x / (width - 1) : 0;
      const value =
        sample(coarse, coarseN, u, v) * 0.62 + sample(fine, fineN, u, v) * 0.38;
      const dither = hash2(x, y, seed) * 0.06 - 0.03;
      const [r, g, b] = hsvToRgb(
        (hueBase + v * 0.22 + value * 0.08) % 1,
        0.28 + value * 0.3,
        0.24 + v * 0.18 + value * 0.42 + dither,
      );
      const offset = (y * width + x) * 4;
      data[offset] = r;
      data[offset + 1] = g;
      data[offset + 2] = b;
      data[offset + 3] = 255;
    }
  }
}

function clamp255(value: number): number {
  return value < 0 ? 0 : value > 255 ? 255 : Math.round(value);
}

/** Encode the page to PNG. Fixed encoder settings so the bytes are a pure function of the seed. */
export async function encodeAtlasPng(pixels: {
  data: Buffer;
  pageSize: number;
  pageHeight?: number;
}): Promise<Buffer> {
  return await sharp(pixels.data, {
    raw: {
      width: pixels.pageSize,
      height: pixels.pageHeight ?? pixels.pageSize,
      channels: 4,
    },
  })
    .png({ compressionLevel: 6, effort: 7, palette: false })
    .toBuffer();
}

export interface AtlasArtifact {
  pngPath: string;
  jsonPath: string;
  seed: number;
  pageSize: number;
  regions: AtlasRegion[];
  bytes: number;
  generated: boolean;
}

/**
 * Cache-or-generate the atlas under `artifacts/perf/fixtures/`. The PNG is multi-MB and generated,
 * so it stays out of git; regeneration only happens when the cached file is missing.
 */
export async function ensureAtlasFixture(
  artifactsDir: string,
  options: AtlasGenerateOptions = {},
): Promise<AtlasArtifact> {
  const {
    seed = ATLAS_DEFAULTS.seed,
    pageSize = ATLAS_DEFAULTS.pageSize,
    regionCount = ATLAS_DEFAULTS.regionCount,
    regionInset = true,
  } = options;
  // The inset variant is a DIFFERENT page, so it gets its own cache stem: silently serving the
  // jittered page for a `scaleDiversity=shared` run would make the isolation measure nothing.
  const stem = `atlas-${seed}-${pageSize}-${regionCount}${regionInset ? "" : "-uniform"}`;
  const pngPath = join(artifactsDir, "fixtures", `${stem}.png`);
  const jsonPath = join(artifactsDir, "fixtures", `${stem}.json`);
  await mkdir(dirname(pngPath), { recursive: true });

  try {
    const [png, json] = await Promise.all([
      readFile(pngPath),
      readFile(jsonPath, "utf8"),
    ]);
    const parsed = JSON.parse(json) as {
      seed: number;
      pageSize: number;
      regions: AtlasRegion[];
    };
    if (parsed.pageSize === pageSize && parsed.regions.length === regionCount) {
      return {
        pngPath,
        jsonPath,
        seed,
        pageSize,
        regions: parsed.regions,
        bytes: png.byteLength,
        generated: false,
      };
    }
  } catch {
    // not cached yet
  }

  const pixels = renderAtlasPixels({
    seed,
    pageSize,
    regionCount,
    regionInset,
  });
  const png = await encodeAtlasPng(pixels);
  await writeFile(pngPath, png);
  await writeFile(
    jsonPath,
    `${JSON.stringify({ seed, pageSize, regions: pixels.regions }, null, 2)}\n`,
  );
  return {
    pngPath,
    jsonPath,
    seed,
    pageSize,
    regions: pixels.regions,
    bytes: png.byteLength,
    generated: true,
  };
}

export interface BackgroundArtifact {
  pngPath: string;
  width: number;
  height: number;
  bytes: number;
  generated: boolean;
}

/**
 * The second fixture: ONE large opaque image, the stand-in for a host-rendered static background
 * (2520x1080 in the consuming project). Same generator, same seeding discipline, same on-disk cache
 * — a separate image pipeline would be a second thing to keep deterministic for no gain.
 *
 * It carries a handful of large shapes over an opaque textured base so it is neither trivially
 * compressible nor transparent: the presence guard must be able to sample it anywhere, and a
 * flat-fill background would decode in a fraction of the time a real one does.
 */
export async function ensureBackgroundFixture(
  artifactsDir: string,
  options: { seed?: number; width: number; height: number; shapes?: number },
): Promise<BackgroundArtifact> {
  const { seed = ATLAS_DEFAULTS.seed, width, height, shapes = 12 } = options;
  const stem = `background-${seed}-${width}x${height}-${shapes}`;
  const pngPath = join(artifactsDir, "fixtures", `${stem}.png`);
  await mkdir(dirname(pngPath), { recursive: true });
  try {
    const png = await readFile(pngPath);
    return { pngPath, width, height, bytes: png.byteLength, generated: false };
  } catch {
    // not cached yet
  }
  const pixels = renderAtlasPixels({
    seed,
    pageSize: width,
    pageHeight: height,
    regionCount: shapes,
    opaqueBase: true,
  });
  const png = await encodeAtlasPng(pixels);
  await writeFile(pngPath, png);
  return { pngPath, width, height, bytes: png.byteLength, generated: true };
}
