extends SceneTree

# The Godot half of the S9 text-rendering round: the same runs, the same font file, the same
# rotation and the same per-frame offsets as the browser arms, measured with Godot's own monitors.
#
# THIS IS A REFERENCE, NOT A COLUMN OF THE BROWSER TABLE. Different process, different renderer,
# different environment — the perf harness refuses cross-environment GPU comparisons everywhere
# else and this is no exception. What Godot uniquely supplies is an EXACT, engine-attributed VRAM
# number (`RENDER_VIDEO_MEM_USED` / `RENDER_TEXTURE_MEM_USED`) and a draw-call count, which is why
# it is worth measuring at all rather than only screenshotting.
#
# THE LAYOUT IS NOT RECOMPUTED HERE. Cell boxes, run strings and the per-frame translation offsets
# all arrive in the manifest, generated by the same pure functions the browser scenario uses
# (`packages/perf-harness/src/scenarios/text-render.ts`). Re-deriving the triangle wave and the
# glyph-pool stride in GDScript would be a second implementation of the geometry, free to drift
# from the one under measurement — and a Godot arm drawing subtly different text would look like a
# rendering difference rather than the bug it is.
#
# Usage:
#   godot --path godot/project --script res://scripts/bench_text.gd -- --manifest /abs/path.json
#
# Needs a REAL DISPLAY (run it under xvfb-run): --headless renders nothing, so every monitor would
# report the cost of drawing no text.

func _initialize() -> void:
	var manifest_path := ""
	var args := OS.get_cmdline_user_args()
	for i in range(args.size()):
		if args[i] == "--manifest" and i + 1 < args.size():
			manifest_path = args[i + 1]
	if manifest_path == "":
		push_error("Usage: godot --path godot/project --script res://scripts/bench_text.gd -- --manifest manifest.json")
		quit(2)
		return

	var manifest_file := FileAccess.open(manifest_path, FileAccess.READ)
	if manifest_file == null:
		push_error("Could not open manifest: " + manifest_path)
		quit(2)
		return
	var parsed: Variant = JSON.parse_string(manifest_file.get_as_text())
	manifest_file.close()
	if not parsed is Dictionary:
		push_error("Manifest must be a JSON object: " + manifest_path)
		quit(2)
		return
	var exit_code := await _run(parsed as Dictionary)
	quit(exit_code)

func _run(manifest: Dictionary) -> int:
	var viewport_width := int(manifest.get("viewportWidth", 1280))
	var viewport_height := int(manifest.get("viewportHeight", 800))
	var font_path := str(manifest.get("fontPath", ""))
	var font_size := int(manifest.get("fontSize", 12))
	var rotation_deg := float(manifest.get("rotationDeg", 10.0))
	var variant := str(manifest.get("variant", "default"))
	var warmup_frames := int(manifest.get("warmupFrames", 30))
	var measure_frames := int(manifest.get("frames", 300))
	var screenshot_path := str(manifest.get("screenshot", ""))
	var screenshot_frame := int(manifest.get("screenshotFrame", measure_frames - 1))
	# One still per listed frame, written as `<stem>-<frame>.png`. This is what lets the fidelity
	# probe ask Godot for the SAME eight sub-pixel translations it asks the browser arms for —
	# without it, Godot could only ever contribute a single still, and its shimmer (the metric the
	# whole round is about) would be permanently unmeasurable.
	var screenshot_frames: Array = manifest.get("screenshotFrames", [])
	var screenshot_stem := str(manifest.get("screenshotStem", ""))
	# JSON numbers parse as FLOAT, and `Array.has(int)` against `[0.0, 1.0, ...]` does not match —
	# which failed silently, wrote no stills, and left the probe to blame a missing file. An int-keyed
	# dictionary compares exactly.
	var wanted_frames := {}
	for wanted in screenshot_frames:
		wanted_frames[int(wanted)] = true
	var output_path := str(manifest.get("output", ""))
	# Px from a run box's TOP EDGE to the alphabetic baseline, when the caller wants every arm
	# anchored the same way (the fidelity probe does; the perf bench leaves it unset and keeps
	# Label's own VERTICAL_ALIGNMENT_TOP placement). Negative means "not requested".
	var baseline := float(manifest.get("baseline", -1.0))
	var runs: Array = manifest.get("runs", [])
	# offsets[frame][run] = {"x": .., "y": ..}, precomputed by the TS side. See the header.
	var offsets: Array = manifest.get("offsets", [])

	if font_path == "" or runs.is_empty() or offsets.is_empty():
		push_error("Manifest needs fontPath, runs and offsets.")
		return 2

	var viewport_size := Vector2i(viewport_width, viewport_height)
	DisplayServer.window_set_size(viewport_size)
	get_root().size = viewport_size
	# Uncap the loop. With vsync on, every frame-time sample would be the refresh interval and the
	# whole timing column would describe the display rather than the text.
	DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_DISABLED)
	Engine.max_fps = 0
	# Match the browser page's background so the two screenshots are comparable without a
	# per-arm background correction, and so a fidelity diff measures glyphs rather than backdrop.
	get_root().transparent_bg = false
	RenderingServer.set_default_clear_color(Color(0x10 / 255.0, 0x10 / 255.0, 0x14 / 255.0, 1.0))

	# The fonts are built in code rather than loaded from a `.tres` so MSDF can be switched on BEFORE
	# a single glyph is rasterized. Setting it on an already-populated FontFile works, but it
	# discards a cache the run then has to rebuild — inside the measured window, on the msdf arm
	# only, which is exactly the sort of asymmetry that makes an arm look expensive for the wrong
	# reason.
	#
	# ONE PER DISTINCT PATH, because a cell now stacks a Han run and a Latin run and each has to be
	# set in its own face. Cached by path so two runs in the same face share one FontFile — and
	# therefore one glyph atlas, which is what `textTextureMemBytes` is measuring.
	var msdf_size := int(manifest.get("msdfSize", 128))
	var msdf_pixel_range := int(manifest.get("msdfPixelRange", 14))
	var fonts := {}
	var font_paths: Array[String] = [font_path]
	for entry_variant in runs:
		var entry: Dictionary = entry_variant
		var run_font_path := str(entry.get("fontPath", ""))
		if run_font_path != "" and not font_paths.has(run_font_path):
			font_paths.append(run_font_path)
	for path in font_paths:
		var font := FontFile.new()
		var load_error := font.load_dynamic_font(path)
		if load_error != OK:
			push_error("Could not load font: " + path)
			return 3
		if variant == "msdf":
			# Godot's OWN FontFile defaults (128 / 14), not a tuned pair: this arm answers "what does
			# a project get when it ticks the checkbox", and 128x128 RGBA per Han glyph is part of
			# that answer rather than a configuration mistake to be optimised away first.
			font.multichannel_signed_distance_field = true
			font.msdf_size = msdf_size
			font.msdf_pixel_range = msdf_pixel_range
		fonts[path] = font
	var font: FontFile = fonts[font_path]
	if variant == "oversample":
		# NOTE: at font size 12 an oversampling of 2 pushes the effective size past
		# SUBPIXEL_POSITIONING_ONE_HALF_MAX_SIZE (20), so Godot turns subpixel positioning OFF for
		# this arm. That is a real consequence of the setting, recorded in the report rather than
		# worked around.
		get_root().set_oversampling_override(float(manifest.get("oversampling", 2.0)))

	var root := Control.new()
	root.name = "BenchRoot"
	root.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	get_root().add_child(root)

	# VRAM BASELINE, measured with the scene up but NO TEXT in it.
	#
	# The totals are not the text's cost: at 1280x800 the Forward+ render targets alone are ~17 MB
	# and have nothing to do with glyphs, so only the DELTA over this baseline is attributable.
	#
	# AND THE TWO MONITORS ARE NOT THE SAME KIND OF NUMBER. `RENDER_TEXTURE_MEM_USED` is
	# `RenderingDevice::MEMORY_TEXTURES` — a real per-resource sum, and the one to read.
	# `RENDER_VIDEO_MEM_USED` is `MEMORY_TOTAL`, the VMA allocator's POOL total, which grows in
	# large blocks and never shrinks (`servers/rendering/renderer_rd/storage_rd/utilities.cpp:295`).
	# Measured here: the msdf arm (+32 MiB of real texture) and the oversample arm (+0.5 MB) both
	# reported the identical +34 MiB of "video memory", because both happened to trip the same one
	# extra pool block. Read as a cost that would have said MSDF and oversampling are equally
	# expensive, which is off by ~64x.
	for _warm in range(3):
		await process_frame
	var baseline_video_mem := Performance.get_monitor(Performance.RENDER_VIDEO_MEM_USED)
	var baseline_texture_mem := Performance.get_monitor(Performance.RENDER_TEXTURE_MEM_USED)
	var baseline_buffer_mem := Performance.get_monitor(Performance.RENDER_BUFFER_MEM_USED)

	var labels: Array[Label] = []
	for entry_variant in runs:
		var entry: Dictionary = entry_variant
		var label := Label.new()
		label.text = str(entry.get("text", ""))
		# The run's OWN face. A run that names none falls back to the manifest's default, which is
		# what keeps a manifest written before this round loadable.
		var run_font: FontFile = fonts.get(str(entry.get("fontPath", "")), font)
		label.add_theme_font_override("font", run_font)
		label.add_theme_font_size_override("font_size", font_size)
		label.add_theme_color_override("font_color", Color(1, 1, 1, 1))
		label.autowrap_mode = TextServer.AUTOWRAP_OFF
		label.position = Vector2(float(entry.get("left", 0.0)), float(entry.get("top", 0.0)))
		var run_size := Vector2(float(entry.get("width", 0.0)), float(entry.get("height", 0.0)))
		label.size = run_size
		# Godot rotates a Control about `pivot_offset`; the browser arms rotate about the run box's
		# centre (`transform-origin: 50% 50%` for a rotation-only Control), so the pivot is centred
		# here to keep the two describing the same transform.
		#
		# FROM `run_size`, NEVER FROM `label.size`. `Control.set_size` CLAMPS to the combined minimum
		# size, and Label's minimum is its own measurement of the text: this 144x16.2 run box came
		# back as 192x23. Reading the pivot back off `label.size` therefore rotated about a point
		# 24 px to the right of the browser's, which at 10 degrees put every glyph 4.2 px too high —
		# a pure vertical error with no vertical cause, invisible at rotation 0 and invisible in the
		# slope. The clamp itself is harmless: the glyphs are laid out from the box's top-left, so a
		# box larger than the run does not move them.
		label.pivot_offset = run_size * 0.5
		label.rotation_degrees = rotation_deg
		root.add_child(label)
		if baseline >= 0.0:
			label.position += _baseline_correction(label, run_font, font_size, baseline, rotation_deg)
		labels.append(label)

	var rest: Array[Vector2] = []
	for label in labels:
		rest.append(label.position)

	# Warmup: rasterize every glyph and let the atlas settle, so the measured window prices STEADY
	# STATE. Without it the first frames carry the whole FreeType pass and the median describes
	# cache population instead of rendering.
	for frame in range(warmup_frames):
		_apply_offsets(labels, rest, offsets[frame % offsets.size()])
		await process_frame

	var frame_ms: Array[float] = []
	var process_ms: Array[float] = []
	var draw_calls: Array[float] = []
	var video_mem: Array[float] = []
	var texture_mem: Array[float] = []
	var buffer_mem: Array[float] = []
	var screenshot_error := OK
	var captured := false
	var previous_usec := Time.get_ticks_usec()

	for frame in range(measure_frames):
		_apply_offsets(labels, rest, offsets[frame % offsets.size()])
		await process_frame
		# WALL TIME between consecutive frames is the honest cost here. `TIME_PROCESS` is reported
		# beside it but must not be read as the frame cost: this script drives the loop from a
		# coroutine resumed by `process_frame`, so the engine attributes the await to the process
		# callback and the monitor reads tens of ms for work an RTX 2060 does in under one.
		var now_usec := Time.get_ticks_usec()
		frame_ms.append(float(now_usec - previous_usec) / 1000.0)
		previous_usec = now_usec
		process_ms.append(Performance.get_monitor(Performance.TIME_PROCESS) * 1000.0)
		draw_calls.append(Performance.get_monitor(Performance.RENDER_TOTAL_DRAW_CALLS_IN_FRAME))
		video_mem.append(Performance.get_monitor(Performance.RENDER_VIDEO_MEM_USED))
		texture_mem.append(Performance.get_monitor(Performance.RENDER_TEXTURE_MEM_USED))
		buffer_mem.append(Performance.get_monitor(Performance.RENDER_BUFFER_MEM_USED))
		if screenshot_path != "" and frame == screenshot_frame and not captured:
			captured = true
			screenshot_error = _capture(screenshot_path, viewport_width, viewport_height)
		if screenshot_stem != "" and wanted_frames.has(frame):
			var stem_error := _capture("%s-%d.png" % [screenshot_stem, frame], viewport_width, viewport_height)
			if stem_error != OK:
				screenshot_error = stem_error

	var report := {
		"schema": "godot-text-bench/1",
		"variant": variant,
		"godot": Engine.get_version_info().get("string", ""),
		"renderer": str(ProjectSettings.get_setting("rendering/renderer/rendering_method", "")),
		"adapter": RenderingServer.get_video_adapter_name(),
		"adapterApi": RenderingServer.get_video_adapter_api_version(),
		"viewport": {"width": viewport_width, "height": viewport_height},
		"fontPath": font_path,
		# Every face this run actually loaded. `script=both` is two, and "which fonts was this" is
		# the first question anyone comparing a VRAM number across runs has to answer.
		"fontPaths": font_paths,
		"fontSize": font_size,
		"rotationDeg": rotation_deg,
		"runs": runs.size(),
		"warmupFrames": warmup_frames,
		"frames": measure_frames,
		"screenshotFrame": screenshot_frame if captured else -1,
		# The three switches that decide what Godot's rasterizer actually does at this size. Recorded
		# even when unset, because "which arm was this" is the first question any reader has.
		"msdf": variant == "msdf",
		"msdfSize": msdf_size if variant == "msdf" else 0,
		"msdfPixelRange": msdf_pixel_range if variant == "msdf" else 0,
		"oversamplingOverride": get_root().get_oversampling_override(),
		"oversampling": get_root().get_oversampling(),
		"subpixelPositioning": int(ProjectSettings.get_setting("gui/theme/default_font_subpixel_positioning", 1)),
		"hinting": int(ProjectSettings.get_setting("gui/theme/default_font_hinting", 1)),
		"antialiasing": int(ProjectSettings.get_setting("gui/theme/default_font_antialiasing", 1)),
		"snap2dTransforms": bool(ProjectSettings.get_setting("rendering/2d/snap/snap_2d_transforms_to_pixel", false)),
		"snap2dVertices": bool(ProjectSettings.get_setting("rendering/2d/snap/snap_2d_vertices_to_pixel", false)),
		"metrics": {
			# The frame cost. Wall time between consecutive frames with vsync off.
			"frameMs": _stat(frame_ms),
			# Reported, and NOT the frame cost — see the loop. Kept because a reader who knows Godot
			# will look for it, and finding it absent is worse than finding it labelled.
			"processMsNotFrameCost": _stat(process_ms),
			"drawCalls": _stat(draw_calls),
			# THE number: a real per-resource texture sum, minus the identical empty scene. Godot is
			# the one place in this round where VRAM is exact and engine-attributed.
			"textTextureMemBytes": _stat(texture_mem)["p50"] - baseline_texture_mem,
			"textBufferMemBytes": _stat(buffer_mem)["p50"] - baseline_buffer_mem,
			# Pool-granular, block-quantised, and NOT a cost — see the baseline comment above.
			"poolVideoMemBytes": _stat(video_mem),
			"textureMemBytes": _stat(texture_mem),
			"bufferMemBytes": _stat(buffer_mem),
			"baselineVideoMemBytes": baseline_video_mem,
			"baselineTextureMemBytes": baseline_texture_mem,
			"baselineBufferMemBytes": baseline_buffer_mem,
			"objectCount": Performance.get_monitor(Performance.OBJECT_COUNT),
		},
	}
	# Always reported, including on the stills path: a capture that failed while the run otherwise
	# succeeded is exactly the failure that reads as "the file is missing" three layers away.
	report["screenshotError"] = screenshot_error
	report["stillsWritten"] = wanted_frames.size() if screenshot_stem != "" else 0
	if screenshot_path != "":
		report["screenshot"] = screenshot_path

	if output_path != "":
		var out := FileAccess.open(output_path, FileAccess.WRITE)
		if out == null:
			push_error("Could not open output: " + output_path)
			return 4
		out.store_string(JSON.stringify(report, "\t"))
		out.close()
	else:
		print(JSON.stringify(report))

	get_root().remove_child(root)
	root.queue_free()
	await process_frame
	if screenshot_error != OK:
		push_error("Could not write screenshot: " + screenshot_path)
		return 5
	return 0

# Move a Label so its FIRST LINE'S ALPHABETIC BASELINE lands `baseline` px below the run box's top
# edge — the same anchor the browser arms use, so a per-pixel diff between them measures the
# rasterizer instead of three engines' disagreeing vertical-layout conventions.
#
# Two things here are easy to get wrong:
#
#   * The label's own baseline is NOT simply `font.get_ascent()`. Label lays a line out at
#     `style.get_offset().y + asc`, where `asc` is the SHAPED line's ascent padded up to the font
#     height when the two disagree (`scene/gui/label.cpp:606-613, 816`). Reproduced here rather
#     than approximated. `line_spacing` does not enter: with VERTICAL_ALIGNMENT_TOP `vbegin` is 0
#     and the spacing is only ever added AFTER a line.
#   * `position` is applied AFTER the rotation about `pivot_offset`, so a shift of `dy` INSIDE the
#     unrotated box is a position delta of `R(theta) * (0, dy)`. Feeding the raw `dy` would slide
#     the run along the wrong axis and pick up a sideways error of `dy * sin(theta)`.
func _baseline_correction(label: Label, font: Font, font_size: int, baseline: float, rotation_deg: float) -> Vector2:
	var asc := font.get_ascent(font_size)
	var dsc := font.get_descent(font_size)
	var font_h := font.get_height(font_size)
	if asc + dsc < font_h:
		asc += (font_h - (asc + dsc)) / 2.0
	var style := label.get_theme_stylebox("normal")
	var style_top := style.get_offset().y if style != null else 0.0
	var dy := baseline - (style_top + asc)
	var rad := deg_to_rad(rotation_deg)
	return Vector2(-dy * sin(rad), dy * cos(rad))

func _capture(path: String, viewport_width: int, viewport_height: int) -> Error:
	var image := get_root().get_texture().get_image()
	if image.get_width() != viewport_width or image.get_height() != viewport_height:
		image = image.get_region(Rect2i(0, 0, viewport_width, viewport_height))
	return image.save_png(path)

func _apply_offsets(labels: Array[Label], rest: Array[Vector2], frame_offsets: Variant) -> void:
	var list: Array = frame_offsets
	for i in range(labels.size()):
		var offset: Dictionary = list[i % list.size()]
		labels[i].position = rest[i] + Vector2(float(offset.get("x", 0.0)), float(offset.get("y", 0.0)))

# Median plus the tails. A mean would let one stalled frame move the number, which is the same
# reason the browser harness reports medians over five repeats rather than averages.
func _stat(values: Array[float]) -> Dictionary:
	if values.is_empty():
		return {"p50": 0.0, "p95": 0.0, "max": 0.0, "n": 0}
	var sorted := values.duplicate()
	sorted.sort()
	return {
		"p50": sorted[int(sorted.size() * 0.5)],
		"p95": sorted[int(min(sorted.size() - 1, sorted.size() * 0.95))],
		"max": sorted[sorted.size() - 1],
		"n": sorted.size(),
	}
